### ISSUE TITLE
Add exception handling to AMQP binding

### ISSUE THREAD

**Issue by hekonsek** [iotbricks/iotbricks#18]

**Comment by ctron** [comment]
Ok so after chatting a bit with @ppatierno my suggestion would be use the AMQP feature of rejecting the message. This way we have a "standard AMQP" way of doing things and don't need to do much definition on the wire side, as there already is an `ErrorCondition` type for doing that.

If that approach is fine, I could start working on implementing this on the server and client binding side.

**Comment by ctron** [comment]
Hono is using HTTP error codes for signaling result conditions. Which I kind of like, but which sometimes also makes things more complicated. But I think we should consider this approach when making a decision.

**Comment by ctron** [comment]
Duplicate of #9 ... as we have some content here, I am closing #9.

**Comment by ppatierno** [comment]
I think that we could define as a Symbol something like HTTP codes (i.e. iot:core:created or something like that). It's worth to think about that.

**Comment by ctron** [comment]
I think we are done here for the moment. If we need something improved we create a new task.
