### ISSUE TITLE
Replace "Date" with "Instant" in Device class

### ISSUE THREAD

**Issue by ctron** [iotbricks/iotbricks#19]
I would like to replace the `Date` type with the new Java 8 `Instant` type in the `Device` object.

`Instant` has a way better API than the old `Date` object and can handle stuff like time zone integration way better.

**Comment by ppatierno** [comment]
Do we need that ? I read about it and it seems to have nanoseconds precision but I don't know if we need such a precision and it needs twice the memory space (two Long fields instead of one)

**Comment by ctron** [comment]
It is less about the precision, more about the much improved API around using timestamps.

**Comment by ctron** [comment]
Done
