### ISSUE TITLE
Remove DeviceRegistry#save operation

### ISSUE THREAD

**Issue by hekonsek** [iotbricks/iotbricks#20]
@dejanb @ctron @ppatierno I'd like to remove `DeviceRegistry#save` and keep create/update operations only. I'd like to do it, to keep API as simple as possible at the early stage of the project.

Is that Ok with you? Any other thoughts?

**Comment by ctron** [comment]
Actually I would like to keep it in. I agree the API should stay simple, but I think it already is rather simplistic :grin: ... however when it comes to storage technologies, it would be good to have this use case of atomic check-or-create.

But I don't have any hard feelings on this. If you want to remove it, then do it. If you are unsure, then keep it 😉

**Comment by hekonsek** [comment]
OK, let's keep it then :) .
